# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
# theme: polarbear

# Custom your favicon.ico in `site/source`
favicon: /favicon.jpeg

url: https://zaf1ro.github.io/

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  # Home: /
  # Categories: /categories
  # Tags: /tags
  # Archives: /archives
  # About: /about
  Github: https://github.com/Zaf1ro

# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>Hello, I am Frost</p>
widget:
  Tags: true
  # Categories: true

# category_depth: 3
# flat_categories: false

widget_custom:
  title: GitHub
  content: https://github.com/Zaf1ro
  Search: Search

# excerpt: false

# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  fancybox: false

# Google Analytics
# google_analytics: UA-147970871-1

# TOC
toc: true

# Disqus
disqus_shortname: zaf1ro

# Version
version: 1.1


